name: model-training
on: [push]
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
      - uses: iterative/setup-cml@v1
      - name: Print CML version
        run: |
          cml --version
      - name: Check if TOKEN exists
        run: |
          if [ -z "${{ secrets.TOKEN }}" ]; then
            echo "TOKEN does not exist."
            exit 1
          else
            echo "TOKEN exists."
          fi
      - name: Train model
        env:
          CML_TOKEN: ${{ secrets.TOKEN }}
        run: |
          pip install -r requirements.txt
          python train.py

          cat metrics.txt >> report.md
          echo "![](./plot.png)" >> report.md
          cml comment update report.md